### ISSUE TITLE
has method

### ISSUE THREAD

**Issue by yuloh** [gamringer/JSONPointer#2]
Hello,

What do you think about adding `$pointer->has('/some/path')`?

**Comment by gamringer** [comment]
I'm all for it. Do you already have a patch to submit ? If not, I can implement it shortly. Meanwhile, since a get() on a non-existant value throws an exception, you can use that as a workaround.

**Comment by yuloh** [comment]
I don't have a patch yet.  I probably won't have time to work on one today so I think you will get to it first.

I have been using the exception workaround but I would prefer to avoid the try catch block.

**Comment by gamringer** [comment]
What do you think of [this commit](https://github.com/gamringer/JSONPointer/commit/b30bb7bb6bf99caa6316794485eda9e2045f8035) ?

**Comment by yuloh** [comment]
Looks good. Thanks for the quick response!
