### ISSUE TITLE
Packagist 3.2 release says it supports 5.6

### ISSUE THREAD

**Issue by yuloh** [gamringer/JSONPointer#4]
It looks like the change from #3 should be backported to the 3.2 branch.  Otherwise packagist will try and install 3.2 even though you are on 5.6.

**Comment by gamringer** [comment]
I re-released 3.2 including your fix. I really don't like having done that, but I really fucked up by forgetting to edit composer.json first. My apologies to any problem caused. The release is exactly the same in every other regard.
